from app.models.word import Word


def test_created_at_is_declared_timezone_aware() -> None:
    """The model must describe the column the database actually has.

    The migration created words.created_at as TIMESTAMP WITH TIME ZONE, but
    the model declared a bare datetime, which maps to a naive DateTime. That
    mismatch makes `alembic check` report drift and, worse, makes the next
    autogenerated migration offer to convert the column to a naive type and
    drop every stored offset.
    """
    column = Word.__table__.c.created_at

    assert column.type.timezone is True


def test_created_at_default_is_timezone_aware() -> None:
    """The Python-side default has to match the column it is written to."""
    word = Word(
        user_id=1,
        word="test",
        translation="тест",
        rank=1,
        rank_range="1-500",
        level="A1",
        frequency=1,
        frequency_group="Core",
        category="Nouns",
        type="word",
    )

    assert word.created_at.tzinfo is not None
