---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: easy-vocab
  namespace: easy-vocab
spec:
  selector:
    app: easy-vocab
  ports:
    - name: http
      port: 80
      targetPort: 5000
